### ISSUE TITLE
Policy exception: change the default no-asm implementation in 3.0 to the faster non-constant time version

### ISSUE THREAD

**Issue by paulidale** [openssl/technical-policies#19]
Topic: OTC approves the OMC request for an exception to the stable release
       policy to allow changing the default AES for no-asm builds from the
       constant time one introduced in PR#10828 to the prior non-constant
       time version.
Proposed by: Tim
Public: yes
Opened: 2022-01-25
Closed: 2022-01-25
Accepted:  yes  (for: 7, against: 1, abstained: 0, not voted: 2)

  Dmitry     [+1]
  Matt       [+1]
  Pauli      [+1]
  Tim        [+1]
  Richard    [+1]
  Shane      [+1]
  Tomas      [+1]
  Kurt       [  ]
  Matthias   [  ]
  Nicola     [-1]

**Comment by kroeckx** [comment]
Our voting policy was not followed for this issue.

**Comment by paulidale** [comment]
Which part?

**Comment by paulidale** [comment]
@t8m [figured it out](https://github.com/openssl/technical-policies/pull/21#discussion_r793425691), I push to the mirror repo not the main one.

**Comment by kroeckx** [comment]
0
