### ISSUE TITLE
VOTE: Accept PR #17998 into master and 3.0 branches

### ISSUE THREAD

**Issue by t8m** [openssl/technical-policies#41]
```
Topic: Accept PR #17998 into master and 3.0 branches
Proposed by: Tomas
Issue link: https://github.com/openssl/technical-policies/issues/41
Public: yes
Opened: 2022-04-07
Closed: 
Accepted:  yes/no  (for: ?, against: ?, abstained: ?, not voted: ?)

  Dmitry     [  ]
  Matt       [  ]
  Pauli      [  ]
  Tim        [  ]
  Richard    [  ]
  Shane      [  ]
  Tomas      [+1]
  Kurt       [  ]
  Matthias   [  ]
  Nicola     [  ]
```

**Comment by t8m** [comment]
I vote [+1] with the rationale that explicit parameters are a potential security problem.

**Comment by levitte** [comment]
vote: [ 0]

**Comment by paulidale** [comment]
Vote: [+1]

I didn't think there was an issue with it going into master.

**Comment by slontis** [comment]
I was not present in the meeting when this was discussed, so may be missing some context.
I am not sure this is the correct way to solve the issue. 
i.e. Why is mapping explicit parameters that match a named curve an issue inside the fips module?
This is a perfectly acceptable thing to do in fips mode. Isn't using explicit params that dont match a named curve the real problem? Is this explicit param to named curve conversion being done elsewhere now?

**Comment by mattcaswell** [comment]
Vote: [ 0]

**Comment by romen** [comment]
Vote: [+1]

**Comment by beldmit** [comment]
Vote: [ 0]

**Comment by mspncp** [comment]
Vote: [+1]

**Comment by fariborz4** [comment]
Hi

**Comment by t-j-h** [comment]
Vote: [ 0 ]

**Comment by kroeckx** [comment]
It's unclear to me why this is a vote. I currently see no arguments of why this isn't a bug fix.

**Comment by paulidale** [comment]
No consensus was reached about this being a bug or not.  It also changes the 3.0 API.

**Comment by fariborz4** [comment]
Hi

**Comment by t8m** [comment]
Everybody has voted. I am closing the vote.

**Comment by t8m** [comment]
```
Topic: Accept PR #17998 into master and 3.0 branches
Proposed by: Tomas
Issue link: https://github.com/openssl/technical-policies/issues/41
Public: yes
Opened: 2022-04-07
Closed: 2022-04-14
Accepted:  yes  (for: 5, against: 0, abstained: 5, not voted: 0)

  Dmitry     [ 0]
  Matt       [ 0]
  Pauli      [+1]
  Tim        [ 0]
  Richard    [ 0]
  Shane      [+1]
  Tomas      [+1]
  Kurt       [ 0]
  Matthias   [+1]
  Nicola     [+1]
```
