### ISSUE TITLE
Documentation requirements

### ISSUE THREAD

**Issue by kroeckx** [openssl/technical-policies#5]
It seems there is at least not an agreement on what all needs to be documented. It would be good to have a policy document so that we can all agree on what is needed.

The only thing I could find that mentions anything about it is the [roadmap](https://www.openssl.org/policies/roadmap.html), which says new public APIs will be documented.

My understanding of what we talked about many years ago is that we want all functions, including internal, to be documented. This means all new functions, public or not, will be documented. The strategy for existing functions, public or not, is that we check/add the documentation when we modify the function.

**Comment by t8m** [comment]
IMO documenting all static functions would be too burdensome. But documenting internal api calls at least roughly makes sense.

**Comment by kroeckx** [comment]
I can agree that some functions don't need to be documented, which might boil down to functions that are 2 lines or less. That a function is static is no indication for me that it should not be documented.

**Comment by mattcaswell** [comment]
OTC: Staff to create a draft policy

**Comment by paulidale** [comment]
First draft in #18

**Comment by levitte** [comment]
#18 has been merged...  shouldn't this issue be closed?
