### ISSUE TITLE
Vote: Accept PR#18407 for backfit to 3.0 as a policy exception.

### ISSUE THREAD

**Issue by romen** [openssl/technical-policies#52]
The topic of this vote is: _Accept [PR#18407](https://github.com/openssl/openssl/pull/18407) for backfit to 3.0 as a policy exception._

The snippet below records the current votes as cast during the weekly OTC meeting (2022-05-31) during which the vote was called.
The vote is still open.

```ossl_vote
Topic: Accept PR#18407 for backfit to 3.0 as a policy exception.
Proposed by: Nicola
Issue link: https://github.com/openssl/technical-policies/issues/52
Public: yes
Opened: 2022-05-31
Closed: 
Accepted:    (for: , against: , abstained: , not voted: )

   Dmitry     [+1]
   Matt       [-1]
   Pauli      [+1]
   Tim        [ 0]
   Richard    [ 0]
   Shane      [-1]
   Tomas      [ 0]
   Kurt       [  ]
   Matthias   [-1]   (corrected)
   Nicola     [+1]
```

**Comment by tmshort** [comment]
-0 from @mspncp ?

**Comment by t8m** [comment]
> -0 from @mspncp ?

Yes, it is possible to vote -0 0 or +0. This is abstention with inclination against or for vote.

**Comment by mspncp** [comment]
> -0 from @mspncp ?

@tmshort please also note that I like your proposed change and consider it an improvement. I'm just inclined against backporting it because I think we should not lightheartedly undermine our own [stable-release-updates](https://github.com/openssl/technical-policies/blob/master/policies/stable-release-updates.md) policy, which we published only recently:

> ![grafik](https://user-images.githubusercontent.com/11467854/171214967-3b972cad-6cf4-4824-9d99-53353d6ff6c4.png)

But you are right, -0 was an indecisive vote. So instead of leaving the decision up to Kurt who hasn't voted yet, I changed my mind and vote explicitly against it:

**Comment by mspncp** [comment]
Vote:   [-1]  (corrected)

**Comment by romen** [comment]
> > -0 from @mspncp ?
> 
> @tmshort please also note that I like your proposed change and consider it an improvement. I'm just inclined against backporting it because I think we should not lightheartedly undermine our own [stable-release-updates](https://github.com/openssl/technical-policies/blob/master/policies/stable-release-updates.md) policy, which we published only recently:
> 
> > ![grafik](https://user-images.githubusercontent.com/11467854/171214967-3b972cad-6cf4-4824-9d99-53353d6ff6c4.png)
> 
> But you are right, -0 was an indecisive vote. So instead of leaving the decision up to Kurt who hasn't voted yet, I changed my mind and vote explicitly against it:

Although openssl/openssl#18407 adds exactly 0 new tests or test cases, so we are not really voting an exception for that part of the policy, rather because we are considering this a new feature (not in the library or binaries, but in the test suite).

I plan to close the vote tomorrow (unless someone else does it sooner) in case there are changes of opinions.

**Comment by tmshort** [comment]
Kurt voted -1; the sum() is -1, so the vote does not pass. I will close #18407 since it has already been merged to master.

**Comment by romen** [comment]
I forgot to record this vote as closed, fixing it now:


```ossl_vote
Topic: Accept PR#18407 for backfit to 3.0 as a policy exception.
Proposed by: Nicola
Issue link: https://github.com/openssl/technical-policies/issues/52
Public: yes
Opened: 2022-05-31
Closed: 2022-06-07
Accepted: no (for: 3, against: 4, abstained: 3, not voted: 0)

   Dmitry     [+1]
   Matt       [-1]
   Pauli      [+1]
   Tim        [ 0]
   Richard    [ 0]
   Shane      [-1]
   Tomas      [ 0]
   Kurt       [-1]
   Matthias   [-1]
   Nicola     [+1]

```
