### ISSUE TITLE
Move technical policies from the website to the repository

### ISSUE THREAD

**Issue by kroeckx** [openssl/technical-policies#6]
At least the coding style should be moved. Not sure if there are others.

**Comment by mattcaswell** [comment]
Related to this - the page https://www.openssl.org/policies/otc-policies.html is now out of date.

**Comment by romen** [comment]
Should https://www.openssl.org/policies/otc-policies.html be updated to point to this repo?

**Comment by paulidale** [comment]
Point that page to https://github.com/openssl/technical-policies/tree/master/policies#readme IMO.  That is, point links to that page to the alternate URL and have a stub page with the link.

**Comment by levitte** [comment]
Has this issue become obsolete?

As for otc-policies, that page literally just pointed here, so is nothing exciting.  openssl/web#312 drops it and generates a better list of links, see https://beta.openssl.org/policies/technical/.  That list is generated from existing policies in this repo.

**Comment by mspncp** [comment]
If everyone agrees with the solution you propose in openssl/web#312, i.e., if your pull request get's merged, then this issue can be closed.

(FWIW:  according to this [help page](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), GitHub supports linking a pull request to an issue in another repository, so you could add a `Fixes openssl/technical-policies#6` annotation to your pull request.)

**Comment by levitte** [comment]
> (FWIW: according to this [help page](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), GitHub supports linking a pull request to an issue in another repository, so you could add a `Fixes openssl/technical-policies#6` annotation to your pull request.)

Good point (and I can confirm this...  I've already used it elsewhere, it even works across different organizations)

**Comment by levitte** [comment]
> > (FWIW: according to this [help page](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), GitHub supports linking a pull request to an issue in another repository, so you could add a `Fixes openssl/technical-policies#6` annotation to your pull request.)
> 
> Good point (and I can confirm this... I've already used it elsewhere, it even works across different organizations)

And done for the commit that actually drops policies/otc-policies.html
