### ISSUE TITLE
vote: The OTC should establish a public communications policy for OTC members

### ISSUE THREAD

**Issue by hlandau** [openssl/technical-policies#88]
```
topic: The OTC should establish a public communications policy for OTC members
Proposed by Tim
Public: yes
opened: 2024-01-23
closed:
accepted:    (for: 2, against: 2, abstained: 3, not voted: 2)

  Dmitry     [  ]
  Matt       [ 0]
  Tim        [+1]
  Hugo       [-1]
  Richard    [+0]
  Shane      [+0]
  Tomas      [+1]
  Kurt       [  ]
  Nicola     [-1]
```

**Comment by kroeckx** [comment]
I currently fail to see why this would be needed, so voting -1

**Comment by hlandau** [comment]
```
topic: The OTC should establish a public communications policy for OTC members
Proposed by Tim
Public: yes
opened: 2024-01-23
closed: 2024-01-25
accepted: no (for: 2, against: 4, abstained: 3, not voted: 0)

  Dmitry     [-1]
  Matt       [ 0]
  Tim        [+1]
  Hugo       [-1]
  Richard    [+0]
  Shane      [+0]
  Tomas      [+1]
  Kurt       [-1]
  Nicola     [-1]
```

**Comment by paulidale** [comment]
Note that this and other votes haven't been merged to the main branch of this repository which violates the voting procedure:

>After the vote is closed the proposer of the vote records the final outcome
and individual member votes in a separate file in the votes subdirectory of
the repository. The commit with the vote record is pushed directly into
the master branch of the repository. No pull request is needed.

**Comment by t8m** [comment]
> Note that this and other votes haven't been merged to the main branch of this repository which violates the voting procedure:

Resolved.
